'use strict';

/**
 * Deterministic Playwright test-stub generator.
 *
 * Turns a ParsedPRD (see prd-parser.js) into a runnable Playwright test suite
 * skeleton:
 *   - <REQ-NNN>.spec.ts   (one `test.describe` per requirement, one `test` per AC,
 *                          Given/When/Then rendered as `test.step()` calls, body is
 *                          `test.fixme()` until filled in test-first)
 *   - .playwright-trace.json  (AC fingerprint manifest — same shape as feature-gen's
 *                          .prd-trace.json, so drift.js's diffDrift works unchanged)
 *
 * Reuses feature-gen's hashAc/normalizeAcText so the fingerprint for a given AC is
 * identical across every generator (Gherkin, Reqnroll, Playwright) -- the same PRD
 * edit registers as drift consistently everywhere, not per-generator.
 *
 * Idempotency: the manifest is always regenerated (deterministic, no timestamps).
 * Spec files are WRITE-ONCE, same as reqnroll-gen.js's Steps/*.cs -- a test body
 * filled in by hand is never clobbered by a later regenerate unless --force is
 * passed, so a PRD edit to one AC can't silently wipe out finished work on its
 * neighbors in the same requirement file.
 */

const fs = require('fs');
const path = require('path');

const { hashAc } = require('./feature-gen');
const { deriveLabel } = require('./prd-parser');

const MANIFEST_NAME = '.playwright-trace.json';

/** Effective display label: the authored one, else a derived fallback. */
function labelFor(prd) {
  return prd.label || deriveLabel(prd.documentId, prd.title);
}

// ---------------------------------------------------------------------------
// TypeScript rendering
// ---------------------------------------------------------------------------

/** Escape a string for embedding inside a single-quoted TS string literal. */
function tsQuote(text) {
  return `'${String(text || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderTest(ac) {
  const hash = hashAc(ac);
  const lines = [];
  lines.push(`  // @${ac.id} @hash:${hash}${ac.needsClarification ? ' @needs-clarification' : ''}`);

  if (!ac.needsClarification && ac.given !== null && ac.given !== undefined) {
    lines.push(`  test(${tsQuote(ac.id)}, async ({ page }) => {`);
    lines.push(`    test.fixme(true, 'Not yet implemented -- fill in test-first');`);
    lines.push(`    await test.step(${tsQuote(`Given ${ac.given}`)}, async () => {});`);
    if (ac.when) lines.push(`    await test.step(${tsQuote(`When ${ac.when}`)}, async () => {});`);
    if (ac.then) lines.push(`    await test.step(${tsQuote(`Then ${ac.then}`)}, async () => {});`);
    for (const extra of ac.ands || []) {
      lines.push(`    await test.step(${tsQuote(`And ${extra}`)}, async () => {});`);
    }
    lines.push('  });');
  } else {
    // Free-form or flagged AC: preserve the prose, stay non-executable until a
    // human clarifies the acceptance criterion (mirrors feature-gen.js's
    // NEEDS CLARIFICATION comment handling).
    lines.push(`  test(${tsQuote(ac.id)}, async () => {`);
    lines.push(`    test.fixme(true, 'NEEDS CLARIFICATION -- not ready for an executable test');`);
    lines.push(`    // ${String(ac.raw || '').replace(/\n/g, ' ')}`);
    lines.push('  });');
  }
  return lines.join('\n');
}

/**
 * Render a single requirement into a .spec.ts document string.
 * @param {import('./prd-parser').ParsedPRD} prd
 * @param {import('./prd-parser').Requirement} req
 */
function renderSpec(prd, req) {
  const out = [];
  out.push(`// ${labelFor(prd)} -- generated from ${prd.documentId || '(no id)'}, ${req.id}`);
  out.push('// Generated by /ensemble:generate-playwright-tests -- do not hand-edit test names/hashes.');
  if (req.moscow || req.complexity) {
    const meta = [
      req.moscow ? `Priority: ${req.moscow}` : null,
      req.complexity ? `Complexity: ${req.complexity}` : null,
    ]
      .filter(Boolean)
      .join(' | ');
    out.push(`// ${meta}`);
  }
  out.push(`import { test } from '@playwright/test';`);
  out.push('');
  out.push(`test.describe(${tsQuote(`${req.id}: ${req.title}`)}, () => {`);
  out.push(req.acs.map(renderTest).join('\n\n'));
  out.push('});');
  return out.join('\n').replace(/\n+$/, '') + '\n';
}

// ---------------------------------------------------------------------------
// Artifact assembly (spec files + manifest), pure
// ---------------------------------------------------------------------------

/**
 * @param {import('./prd-parser').ParsedPRD} prd
 * @param {string} slug   stable output-dir name (PRD filename stem)
 * @param {Object} [opts]
 * @param {string} [opts.prdPath] original PRD path recorded in the manifest
 */
function buildArtifacts(prd, slug, opts = {}) {
  const files = [];
  const acs = {};
  for (const req of prd.reqs) {
    if (!req.acs.length) continue;
    const relPath = `${req.id}.spec.ts`;
    files.push({ relPath, content: renderSpec(prd, req) });
    for (const ac of req.acs) {
      acs[ac.id] = {
        req: req.id,
        hash: hashAc(ac),
        spec_file: relPath,
        needs_clarification: !!ac.needsClarification,
      };
    }
  }
  const manifest = {
    prd: {
      document_id: prd.documentId || null,
      label: labelFor(prd),
      version: prd.version || null,
      path: opts.prdPath || null,
    },
    acs,
  };
  return { slug, files, manifest };
}

// ---------------------------------------------------------------------------
// Disk I/O — atomic, idempotent (same pattern as feature-gen.js)
// ---------------------------------------------------------------------------

function writeFileAtomic(filePath, content) {
  const tmp = `${filePath}.tmp-${process.pid}`;
  fs.writeFileSync(tmp, content);
  fs.renameSync(tmp, filePath);
}

/**
 * Write spec files + manifest under `<outRoot>/<slug>/`.
 * WRITE-ONCE: an existing <REQ-NNN>.spec.ts is never overwritten unless
 * opts.force -- mirrors reqnroll-gen.js's Steps/*.cs handling.
 * @returns {{ outDir:string, written:string[], skipped:string[], planned:string[] }}
 */
function writeArtifacts(prd, slug, outRoot, opts = {}) {
  const artifacts = buildArtifacts(prd, slug, opts);
  const outDir = path.join(outRoot, slug);
  const manifestText = JSON.stringify(artifacts.manifest, null, 2) + '\n';
  const planned = artifacts.files
    .map((f) => path.join(outDir, f.relPath))
    .concat(path.join(outDir, MANIFEST_NAME));

  if (opts.dryRun) {
    return { outDir, written: [], skipped: [], planned };
  }

  fs.mkdirSync(outDir, { recursive: true });
  const written = [];
  const skipped = [];
  for (const f of artifacts.files) {
    const dest = path.join(outDir, f.relPath);
    if (fs.existsSync(dest) && !opts.force) {
      skipped.push(dest);
      continue;
    }
    writeFileAtomic(dest, f.content);
    written.push(dest);
  }
  const manifestPath = path.join(outDir, MANIFEST_NAME);
  writeFileAtomic(manifestPath, manifestText);
  written.push(manifestPath);
  return { outDir, written, skipped, planned };
}

module.exports = {
  tsQuote,
  renderTest,
  renderSpec,
  buildArtifacts,
  writeArtifacts,
  MANIFEST_NAME,
};
